apiVersion: v1
kind: PersistentVolume
metadata:
  name: nodeapp-test-vol
  labels:
    type: local
spec:
  storageClassName: manual # can give any name
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/nodeapp-test"
